### ISSUE TITLE
SendScreenshotNotification not working

### ISSUE THREAD

**Issue by SuperZombi** [KurimuzonAkuma/pyrogram#40]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

On the official version of pyrogram (2.0.106), the notification for sending screenshots worked.
Doesn't work on your fork (2.1.16)

### Steps to reproduce

```python
client.invoke(SendScreenshotNotification(
	  peer=client.resolve_peer(message.chat.id),
	  reply_to_msg_id=message.id,
	  random_id=app.rnd_id()
))
```
```
TypeError: SendScreenshotNotification.__init__() got an unexpected keyword argument 'reply_to_msg_id'
```
<br>

I tried changing the attribute name:
```python
client.invoke(SendScreenshotNotification(
	  peer=client.resolve_peer(message.chat.id),
	  reply_to=message.id,
	  random_id=app.rnd_id()
))
```
```
File "pyrogram\raw\functions\messages\send_screenshot_notification.py", line 84, in write
  b.write(self.reply_to.write())
          ^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'write'
```
But it still doesn't work

**Comment by KurimuzonAkuma** [comment]
Все работает, просто ты не так юзаешь. reply_to принимает тип raw.base.InputReplyTo, а ты пихаешь инт...

**Comment by SuperZombi** [comment]
Found a solution. Need to use `get_reply_to`:
```python
from pyrogram.raw.functions.messages import SendScreenshotNotification
from pyrogram.utils import get_reply_to

client.invoke(SendScreenshotNotification(
	  peer=client.resolve_peer(message.chat.id),
	  reply_to=get_reply_to(reply_to_message_id=message.id),
	  random_id=client.rnd_id()
))
```

**Comment by SuperZombi** [comment]
Вобще я предлагаю сделать по нормальному функцию, чтобы это выглядело примерно вот так:
```python
SendScreenshotNotification(
	  user_id=message.chat.id
)
```
